apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'trivy'
        static_configs:
          - targets: ['trivy-operator.trivy-system.svc.cluster.local:80']
